In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
airbnb = pd.read_csv('paris_airbnb/paris_airbnb.csv')

In [14]:
# pour afficher ls 5 premier ligne 
airbnb.head(5)

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
0,100%,NaN,1.0,48.83349,2.31852,Paris,75014,Île-de-France,2,Entire home/apt,0.0,1.0,0.0,$75.00,$50.00,$0.00,3,15,8
1,100%,NaN,1.0,48.85100,2.35869,Paris,75004,Ile-de-France,2,Entire home/apt,0.0,1.0,1.0,$115.00,$36.00,$0.00,1,90,173
2,100%,NaN,2.0,48.85758,2.35275,Paris,75004,Île-de-France,4,Entire home/apt,2.0,1.0,2.0,$115.00,$50.00,$200.00,10,23,243
3,100%,NaN,1.0,48.86528,2.39326,Paris,75020,Ile-de-France,3,Entire home/apt,1.0,1.0,1.0,$90.00,NaN,NaN,3,365,1
4,67%,NaN,3.0,48.85899,2.34735,Paris,75001,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$75.00,$200.00,"$1,500.00",180,365,0

In [16]:
# pour afficher ls 5 derniere ligne 
airbnb.tail(5)

,host_response_rate,host_acceptance_rate,host_listings_count,latitude,longitude,city,zipcode,state,accommodates,room_type,bedrooms,bathrooms,beds,price,cleaning_fee,security_deposit,minimum_nights,maximum_nights,number_of_reviews
7995,100%,NaN,2.0,48.87901,2.29526,Paris,75017,Île-de-France,2,Entire home/apt,0.0,1.0,1.0,$55.00,$45.00,$400.00,150,1125,0
7996,NaN,NaN,1.0,48.88903,2.35271,Paris,75018,Île-de-France,4,Entire home/apt,1.0,1.0,2.0,$60.00,$20.00,$100.00,3,1125,4
7997,100%,NaN,1.0,48.85313,2.34146,Paris,75006,Île-de-France,2,Entire home/apt,1.0,1.0,1.0,$60.00,$30.00,$0.00,2,10,25
7998,NaN,NaN,1.0,48.88066,2.33639,Paris,75009,Île-de-France,2,Entire home/apt,NaN,1.0,1.0,$58.00,NaN,$200.00,3,9,57
7999,100%,NaN,2.0,48.85760,2.39946,Paris,75020,Île-de-France,6,Entire home/apt,1.0,1.0,3.0,$40.00,$35.00,$300.00,4,1125,49

In [18]:
# pour avoir des infos sur chaque variable
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   host_response_rate    5000 non-null   object
 1   host_acceptance_rate  0 non-null      float64
 2   host_listings_count   7999 non-null   float64
 3   latitude              8000 non-null   float64
 4   longitude             8000 non-null   float64
 5   city                  7997 non-null   object
 6   zipcode               7930 non-null   object
 7   state                 7977 non-null   object
 8   accommodates          8000 non-null   int64
 9   room_type             8000 non-null   object
 10  bedrooms              7976 non-null   float64
 11  bathrooms             7942 non-null   float64
 12  beds                  7986 non-null   float64
 13  price                 8000 non-null   object
 14  cleaning_fee          6250 non-null   object
 15  security_deposit      6320 non-null   object
 16  minimum_nights        8000 non-null   int64
 17  maximum_nights        8000 non-null   int64
 18  number_of_reviews     8000 non-null   int64
dtypes: float64(7), int64(4), object(8)
memory usage: 1.2+ MB

In [20]:
airbnb['beds']

0       0.0
1       1.0
2       2.0
3       1.0
4       1.0
       ...
7995    1.0
7996    2.0
7997    1.0
7998    1.0
7999    3.0
Name: beds, Length: 8000, dtype: float64

In [23]:
airbnb[['beds' , 'bedrooms']].mean()

beds        1.753068
bedrooms    1.248370
dtype: float64

In [26]:
airbnb.columns

Index(['host_response_rate', 'host_acceptance_rate', 'host_listings_count',
       'latitude', 'longitude', 'city', 'zipcode', 'state', 'accommodates',
       'room_type', 'bedrooms', 'bathrooms', 'beds', 'price', 'cleaning_fee',
       'security_deposit', 'minimum_nights', 'maximum_nights',
       'number_of_reviews'],
      dtype='object')

In [29]:
airbnb.iloc[0]

host_response_rate                 100%
host_acceptance_rate                NaN
host_listings_count                 1.0
latitude                       48.83349
longitude                       2.31852
city                              Paris
zipcode                           75014
state                     Île-de-France
accommodates                          2
room_type               Entire home/apt
bedrooms                            0.0
bathrooms                           1.0
beds                                0.0
price                            $75.00
cleaning_fee                     $50.00
security_deposit                  $0.00
minimum_nights                        3
maximum_nights                       15
number_of_reviews                     8
Name: 0, dtype: object

In [30]:
def ma_fontion(dataset , our_acc_value = 3):
    dataset['accommodates'] -= our_acc_value

In [31]:
our_acc_value = 3
airbnb.apply( ma_fontion , axis=0 )

KeyError: 'accommodates'